### ISSUE TITLE
Fails to compile with serde v1.0.119

### ISSUE THREAD

**Issue by c1wren** [wyyerd/stripe-rs#158]
In serde v1.0.119, it is no longer possible to compile because ```serde::private``` is now a private module. The compiler fails at 
```use serde::private::de::{Content, ContentRefDeserializer};```
 which is this line: https://github.com/wyyerd/stripe-rs/blob/58c06e798d52bf8a6398b1d556be93e9dce95f7b/src/resources/payment_source.rs#L30

**Comment by seanpianka** [comment]
[This issue has a fix](https://github.com/Metaswitch/swagger-rs/pull/135)

**Comment by jonahbron** [comment]
To be more explicit, the workaround (or what worked for me) was to point to @seanpianka 's fork, and update my own project to depend on the same Serde versions.

```toml
stripe-rust = { git = "https://github.com/seanpianka/stripe-rs.git", branch = "fix-serde" }
serde = "<1.0.118, >=1.0.79"
serde_derive = "<1.0.118, >=1.0.79"
```
