### ISSUE TITLE
Error `struct import `PaymentIntent` is private`

### ISSUE THREAD

**Issue by kushwahashiv** [wyyerd/stripe-rs#198]
why I'm keep getting error: struct import `PaymentIntent` is private ? even though it defined `pub`.

cargo.toml
```toml
[dependencies]
stripe-rust = { git = "https://github.com/wyyerd/stripe-rs", rev = "efdd5ad" }
```
